source_schema: <<REPLACE ME>>
target_schema: <<REPLACE ME>>
target_tables:
- primary_key: <<REPLACE ME>>
  source_scd_type: 0
  source_table: <<REPLACE ME>>
  target_scd_type: 2
  target_table: RSRCE_ITM
- primary_key: <<REPLACE ME>>
  source_scd_type: 0
  source_table: <<REPLACE ME>>
  target_scd_type: 2
  target_table: EV
- primary_key: <<REPLACE ME>>
  source_scd_type: 0
  source_table: <<REPLACE ME>>
  target_scd_type: 2
  target_table: AR_TRANSLATION
- primary_key: <<REPLACE ME>>
  source_scd_type: 0
  source_table: <<REPLACE ME>>
  target_scd_type: 2
  target_table: CLSIF
